#!/usr/bin/env bash
# Writes .env with freshly generated local credentials.
# An existing .env is never overwritten; keys added in later versions (e.g. OAD_API_TOKEN)
# are appended if missing, existing values stay untouched.
set -euo pipefail
cd "$(dirname "$0")/.."

rand() { LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c "$1"; }
umask 077

if [[ ! -f .env ]]; then
  cat > .env <<EOF
# Generated by scripts/init-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Local development only.
POSTGRES_USER=oad
POSTGRES_PASSWORD=$(rand 32)
POSTGRES_DB=oad

OAD_S3_ACCESS_KEY=oad$(rand 13)
OAD_S3_SECRET_KEY=$(rand 40)
OAD_S3_BUCKET=oad-assets
# Pre-signed URLs are signed for this endpoint (host-side MCP clients)
OAD_S3_PUBLIC_ENDPOINT=http://127.0.0.1:8333

OAD_EMBED_MODEL=nomic-embed-text
OAD_EMBED_DIM=768

# Development identity: the gateway has no OAuth yet (planned for v0.1 hardening).
# Every tool call runs as this actor with these principals. Empty principals = sees nothing.
OAD_DEV_TENANT=00000000-0000-0000-0000-000000000001
OAD_DEV_ACTOR=dev@localhost
OAD_DEV_PRINCIPALS=group:everyone
EOF
  echo "wrote .env"
fi

# --- upgrade path: add keys introduced after the first run ------------------------------
if ! grep -q '^OAD_API_TOKEN=' .env; then
  {
    echo ""
    echo "# Bearer token for the HTTP transport (LibreChat & other network clients)."
    echo "# Clients send: Authorization: Bearer <token>. Not needed for Claude Desktop (stdio)."
    echo "OAD_API_TOKEN=oad_$(rand 48)"
  } >> .env
  echo "added OAD_API_TOKEN to .env"
fi
